
[build]
  publish = "dist"
  command = "npm run build"

# CRITICAL: AdMob app-ads.txt file - ABSOLUTE HIGHEST PRIORITY
[[redirects]]
  from = "/app-ads.txt"
  to = "/app-ads.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain; charset=utf-8", Cache-Control = "public, max-age=86400", X-Robots-Tag = "noindex"}

[[redirects]]
  from = "/.well-known/app-ads.txt"
  to = "/.well-known/app-ads.txt"  
  status = 200
  force = true
  headers = {Content-Type = "text/plain; charset=utf-8", Cache-Control = "public, max-age=86400"}

# Other critical static files
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
  headers = {Content-Type = "text/plain; charset=utf-8"}

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true

# All static file extensions - MUST come before SPA routing
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"], Country = ["US"]}
  headers = {}
  query = {}
  signed = ""
  edge_handler = ""
  
[[redirects]]
  from = "/*.txt"
  to = "/:splat.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = true

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = true

# SPA fallback - LOWEST priority (only for routes that don't match files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Force static file processing
[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=86400"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"
