
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/app-ads.txt"
  to = "/app-ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"  
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico" 
  status = 200
  force = true

[[redirects]]
  from = "/*.txt"
  to = "/:splat.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = true

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
